### ISSUE TITLE
Drawing issue

### ISSUE THREAD

**Issue by rbniranjan** [dblapps/DAScratchPad#2]
Hi .

I am using your code for drawing on image it is working good in simulator iOS7, iOS6 or iOS5,

Main problem is this when i run that code in device with iOS7 it is not working correclty it draw line but very slow. Please help me.

**Comment by dblapps** [comment]
Just tested running on iOS 7 (and building with both Xcode 4.6 and Xcode 5), and I'm not seeing any issues with slow drawing.  Perhaps you can provide some more details or some code to help track down the problem?  Thanks.

**Comment by rbniranjan** [comment]
Hello Thanks for reply,

Please check on device with iOS7 and Xcode should be 4.6.

On Sat, Sep 28, 2013 at 5:00 AM, David B Levi notifications@github.comwrote:

> Just tested running on iOS 7 (and building with both Xcode 4.6 and Xcode
> 5), and I'm not seeing any issues with slow drawing. Perhaps you can
> provide some more details or some code to help track down the problem?
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dblapps/DAScratchPad/issues/2#issuecomment-25284377
> .

## 

Thanks & Regards

R.B Niranjan
Software Engineer

Email: niranjan9795@gmail.com
Ph. No : +919716281084
Skype id: raja_chrome

**Comment by dblapps** [comment]
I did already test on iOS 7 built using Xcode 4.6 on an iPod Touch, and didn't see any problems.  You'll have to give me more details:
- specific device type
- samples of your code

**Comment by dblapps** [comment]
Unable to ever reproduce this, so closing the issue.
