### ISSUE TITLE
Problem drawing on cropped images

### ISSUE THREAD

**Issue by jaredgross** [dblapps/DAScratchPad#3]
Hi,
I am having trouble with drawing on cropped images using your code. If the mainImage is not exactly equal to the screen size then I have proportional distortion problems. You can see my problem here http://stackoverflow.com/questions/22521928/cgcontextdrawimage-distorts-proportions

I was wondering if you could help me out in any way. Thanks for the code, and any suggestions you may have.

**Comment by dblapps** [comment]
Hi,
Just saw this issue (been out with a cold) ... looks like you have it resolved on stackoverflow, so I'm going to mark it as closed.  Let me know if you have any other issues.
Dave
